services:
  payload:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rays
    volumes:
      - ./media:/app/media
    ports:
      - "3333:3000"
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - PAYLOAD_SECRET=secret
      - DATABASE_URL=postgresql://rays:1234@db/dbrays
      - NEXT_PUBLIC_SERVER_URL https://raystrading.com
      - NEXT_PUBLIC_ORG_NAME Raystrading
    networks:
      - default-net

  db:
    image: docker.io/library/postgres:latest
    environment:
      - POSTGRES_USER=rays
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=dbrays
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - default-net
volumes:
  postgres-data:


networks:
  default-net:
    driver: bridge
