services:
  payload:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payload-cms
    volumes:
      - ./media:/app/media
    ports:
      - "3002:3002"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ".env"
    restart: unless-stopped
